import type { Opportunity } from "./types"

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "Desarrollador Full Stack",
    company: "Tech Solutions CR",
    companyId: "company-1",
    location: "San José",
    type: "job",
    status: "active",
    description:
      "Buscamos un desarrollador full stack con experiencia en React y Node.js para unirse a nuestro equipo de desarrollo. Trabajarás en proyectos innovadores para clientes nacionales e internacionales.",
    salary: "₡1,200,000 - ₡1,800,000",
    postedAt: "Hace 3 días",
    requirements: [
      "Experiencia mínima de 2 años en desarrollo web",
      "Conocimientos sólidos en React y Node.js",
      "Experiencia con bases de datos SQL y NoSQL",
    ],
  },
  {
    id: "2",
    title: "Práctica en Análisis de Datos",
    company: "Data Analytics Inc",
    companyId: "company-2",
    location: "Cartago",
    type: "internship",
    status: "active",
    description:
      "Oportunidad de práctica profesional en análisis de datos y visualización con herramientas modernas. Aprenderás sobre Python, SQL y herramientas de visualización.",
    postedAt: "Hace 1 semana",
    requirements: ["Estudiante activo del TEC", "Conocimientos básicos en Python", "Interés en ciencia de datos"],
  },
  {
    id: "3",
    title: "Proyecto: Sistema de Gestión Hospitalaria",
    company: "Hospital Clínica Bíblica",
    companyId: "company-3",
    location: "San José",
    type: "graduation-project",
    status: "active",
    description:
      "Desarrollo de un sistema de gestión hospitalaria con tecnologías web modernas. El proyecto incluirá módulos de pacientes, citas, farmacia e inventario.",
    postedAt: "Hace 2 días",
    requirements: [
      "Estudiante de último año",
      "Conocimientos en desarrollo web",
      "Disponibilidad para trabajo en sitio",
    ],
  },
  {
    id: "4",
    title: "Ingeniero de Software Senior",
    company: "Amazon Web Services",
    companyId: "company-4",
    location: "Remoto",
    type: "job",
    status: "active",
    description:
      "Posición senior en AWS para trabajar en servicios cloud de alta escala. Trabajarás con tecnologías de vanguardia en infraestructura distribuida.",
    salary: "₡3,000,000 - ₡4,500,000",
    postedAt: "Hace 5 días",
    requirements: ["5+ años de experiencia", "Experiencia con servicios cloud", "Inglés avanzado"],
  },
  {
    id: "5",
    title: "Práctica en Ciberseguridad",
    company: "SecureTech",
    companyId: "company-5",
    location: "Heredia",
    type: "internship",
    status: "active",
    description:
      "Práctica en el área de ciberseguridad, trabajando con tecnologías de protección de datos y análisis de vulnerabilidades.",
    postedAt: "Hace 4 días",
    requirements: [
      "Estudiante de Ingeniería en Computación",
      "Interés en seguridad informática",
      "Conocimientos básicos de redes",
    ],
  },
  {
    id: "6",
    title: "Desarrollador Mobile iOS/Android",
    company: "MobileFirst CR",
    companyId: "company-6",
    location: "San José",
    type: "job",
    status: "active",
    description:
      "Desarrollo de aplicaciones móviles nativas para iOS y Android. Trabajarás en aplicaciones empresariales y de consumo.",
    salary: "₡1,500,000 - ₡2,200,000",
    postedAt: "Hace 1 semana",
    requirements: ["Experiencia con Swift o Kotlin", "Portfolio de apps publicadas", "Conocimientos de UI/UX móvil"],
  },
  {
    id: "7",
    title: "Proyecto: App de Gestión Académica",
    company: "Universidad de Costa Rica",
    companyId: "company-7",
    location: "San Pedro",
    type: "graduation-project",
    status: "active",
    description:
      "Desarrollo de una aplicación móvil para gestión académica estudiantil. Incluirá matrícula, horarios, notas y comunicación con profesores.",
    postedAt: "Hace 6 días",
    requirements: ["Estudiante de último año", "Experiencia en desarrollo móvil", "Conocimientos en APIs REST"],
  },
  {
    id: "8",
    title: "Especialista en DevOps",
    company: "Cloud Services Inc",
    companyId: "company-8",
    location: "Remoto",
    type: "job",
    status: "active",
    description:
      "Buscamos especialista en DevOps para gestionar infraestructura cloud y pipelines de CI/CD. Trabajarás con AWS, Docker y Kubernetes.",
    salary: "₡2,000,000 - ₡3,000,000",
    postedAt: "Hace 2 días",
    requirements: ["Experiencia con AWS o GCP", "Conocimientos de Docker y Kubernetes", "Experiencia con CI/CD"],
  },
  {
    id: "9",
    title: "Práctica en Desarrollo Frontend",
    company: "Digital Marketing Solutions",
    companyId: "company-9",
    location: "San José",
    type: "internship",
    status: "active",
    description:
      "Práctica profesional en desarrollo frontend con React. Trabajarás en proyectos web para diversos clientes del sector empresarial.",
    postedAt: "Hace 3 días",
    requirements: ["Estudiante activo", "Conocimientos en React", "HTML, CSS y JavaScript"],
  },
]
